#!/bin/bash

pac_upd() {
    dwmstatus_upd="Upd $(pacman -Qqu --dbpath /tmp/checkup-db-prole/ | wc -l)"
}

date_upd() {
    sdate="$(date +"%B") $(date +"%d")"
}

pac_upd
date_upd

while true; do

minute=$(date +"%-M")
minute_rem=$((minute % 5))
date_check=$(date +"%-H")

if ((minute_rem == 0)); then
    pac_upd
fi

if ((date_check == 23)) && ((minute >= 59)); then
    date_upd
fi
    

vol="Vol $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
volstat=$(amixer get Master | tail -n 1 | cut -d' ' -f 8-)

stime="$(date +"%I"):$(date +"%M"):$(date +"%S")"


if [[ $volstat = off ]];
then
    vol="Vol --%"
fi

out="${dwmstatus_upd} ${vol} ${sdate} ${stime} "
xsetroot -name "${out}"

sleep 1s

done
