#!/bin/bash

numlines=0
file='/tmp/pbstats'

if [[ "$@" == 'songstart' ]]; then

    if [[ -s "$file" ]]; then
        rm -f "$file"
    fi

    while read -r line
    do
        if ((numlines == 0)); then
            echo -n "${line:7} - " >> "$file"
            numlines=$((numlines+1))
        elif ((numlines == 1)); then
            echo -n "${line:6} |" >> "$file"
            numlines=$((numlines+1))
        fi
    done

fi
