#!/bin/bash

numlines=0
file='/tmp/pbstats'

if [[ "$@" == 'songstart' ]]; then

    if [[ -s "$file" ]]; then
        rm -f "$file"
    fi

    while read -r line
    do
        if ((numlines <= 1)); then
            echo "$line" >> "$file"
            numlines=$((numlines+1))
        fi
    done

    sed -i 's/=/=\"/g' "$file"
    sed -i 's/$/\"/g' "$file"

fi
