#!/bin/bash

file='/tmp/pbstats'

pac_upd() {
    dwmstatus_upd="Upd $(pacman -Qqu --dbpath /tmp/checkup-db-prole/ | wc -l)"
}

date_upd() {
    sdate="$(date +"%A") $(date +"%B") $(date +"%d")"
}

runs() {
    if (($(pgrep -c "$1") > 0)); then
        return 0
    else
        return 1
    fi
}

mus_stat() {
    if runs "pianobar" || runs "pianobar"; then
        if [[ -s "$file" ]]; then
            mus=" $(<$file)"
        fi
    elif runs "cmus"; then
        local pre_title="$(cmus-remote -Q | grep 'tag title')"
        local pre_artist="$(cmus-remote -Q | grep 'tag artist')"
        mus="${pre_artist:10} - ${pre_title:9} |"
    else
        mus=''
    fi
}

tmux_stat() {
    tmux_list=''

    if runs "tmux"; then
        local winlist=$(tmux list-windows -F "#{?window_active,+,-}#{window_index}:#{window_name}")

        while read -r line; do
            if [[ "${line:0:1}" == '+' ]]; then
                tmux_list="$tmux_list${line:1} "
            else
                tmux_list="$tmux_list${line:1} "
            fi
        done <<< "$winlist"
    fi
}

vol_stat() {
    local prevol="$(amixer get Master | tail -n 1)"

    if [[ $prevol = *off* ]]; then
        vol="Vol --%"
    else
        prevol2="${prevol#*[}"
        vol="Vol ${prevol2%%]*}"
    fi
}
    
pac_upd
date_upd

while true; do

    minute=$(date +"%-M")
    minute_rem=$((minute % 5))
    date_check=$(date +"%-H")

    if ((minute_rem == 0)); then
        pac_upd
    fi

    if ((date_check == 23)) && ((minute >= 59)); then
        date_upd
    fi

    stime="$(date +"%I"):$(date +"%M"):$(date +"%S")"

    mus_stat
    tmux_stat
    vol_stat

    out="${tmux_list}|${mus} ${dwmstatus_upd} | ${vol} | ${sdate} | ${stime} "
    xsetroot -name "${out}"

    sleep 1s

done
